"""Stable, machine-readable reason codes for Policy & Intervention Engine.

Reason codes describe observed conditions, verifiable evidence relationships,
and threat mechanics. They NEVER state unsupported accusations or legal adjudications.
"""

from enum import Enum


class ReasonCode(str, Enum):
    # Baseline / Informational
    NO_INTERVENTION_REQUIRED = "NO_INTERVENTION_REQUIRED"
    FINANCIAL_CONTENT_DETECTED = "FINANCIAL_CONTENT_DETECTED"
    FINANCIAL_EDUCATION_INFORMATIONAL = "FINANCIAL_EDUCATION_INFORMATIONAL"
    OPINION_OR_PREDICTION_DISCLOSED = "OPINION_OR_PREDICTION_DISCLOSED"

    # Regulatory & Identity Evidence
    UNVERIFIED_REGULATORY_CLAIM = "UNVERIFIED_REGULATORY_CLAIM"
    IDENTITY_NOT_ESTABLISHED = "IDENTITY_NOT_ESTABLISHED"
    IDENTITY_MISMATCH_DETECTED = "IDENTITY_MISMATCH_DETECTED"
    REGULATORY_CONFLICT = "REGULATORY_CONFLICT"
    FACTUAL_CONTRADICTION = "FACTUAL_CONTRADICTION"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"

    # Claims & Return Language
    GUARANTEED_RETURN_LANGUAGE = "GUARANTEED_RETURN_LANGUAGE"
    UNREALISTIC_RETURN_CLAIM = "UNREALISTIC_RETURN_CLAIM"
    URGENCY_FOMO_LANGUAGE = "URGENCY_FOMO_LANGUAGE"

    # Consequential Actions
    PRIVATE_CHANNEL_MIGRATION = "PRIVATE_CHANNEL_MIGRATION"
    EXTERNAL_APP_INSTALLATION = "EXTERNAL_APP_INSTALLATION"
    CREDENTIAL_ACCESS_REQUEST = "CREDENTIAL_ACCESS_REQUEST"
    ACCOUNT_AUTHORIZATION_REQUEST = "ACCOUNT_AUTHORIZATION_REQUEST"
    PAYMENT_REQUEST = "PAYMENT_REQUEST"
    HIGH_IMPACT_ACTION = "HIGH_IMPACT_ACTION"
    IRREVERSIBLE_ACTION_DETECTED = "IRREVERSIBLE_ACTION_DETECTED"
    DANGEROUS_ACTION_SEQUENCE = "DANGEROUS_ACTION_SEQUENCE"

    # Threat & Attack Path Patterns
    AUTHORITY_IMPERSONATION_DETECTED = "AUTHORITY_IMPERSONATION_DETECTED"
    MULTI_SIGNAL_THREAT_PATTERN = "MULTI_SIGNAL_THREAT_PATTERN"
    EVIDENCE_WEAKNESS_COMBINATION = "EVIDENCE_WEAKNESS_COMBINATION"
    TRUST_EXPLOITATION_SEQUENCE = "TRUST_EXPLOITATION_SEQUENCE"

    # Collective Intelligence / Fingerprints
    KNOWN_THREAT_EXACT_MATCH = "KNOWN_THREAT_EXACT_MATCH"
    KNOWN_THREAT_STRUCTURAL_MATCH = "KNOWN_THREAT_STRUCTURAL_MATCH"
    KNOWN_THREAT_SEMANTIC_VARIANT = "KNOWN_THREAT_SEMANTIC_VARIANT"
    KNOWN_THREAT_RELATED_PATTERN = "KNOWN_THREAT_RELATED_PATTERN"

    # Intervention & Control Flow
    USER_CONFIRMATION_REQUIRED = "USER_CONFIRMATION_REQUIRED"
    POLICY_ESCALATION = "POLICY_ESCALATION"
    USER_OVERRIDE_APPLIED = "USER_OVERRIDE_APPLIED"

    # Behavioural Signal Intelligence (Engine 10)
    RAPID_ACTION_ESCALATION = "RAPID_ACTION_ESCALATION"
    LOW_TO_HIGH_IMPACT_TRANSITION = "LOW_TO_HIGH_IMPACT_TRANSITION"
    INFORMATION_TO_TRANSACTION_SHIFT = "INFORMATION_TO_TRANSACTION_SHIFT"
    PERSISTENT_PAYMENT_REQUEST = "PERSISTENT_PAYMENT_REQUEST"
    RETRY_AFTER_DECLINE = "RETRY_AFTER_DECLINE"
    REPEATED_URGENCY = "REPEATED_URGENCY"
