"""Nivesh Firewall — Engine 1: Content Intelligence Engine.

Converts raw user-provided financial content into clean, normalized,
structured representation for downstream security engines.
"""

from .engine import ContentIntelligenceEngine, ENGINE_VERSION
from .claims import ClaimIntelligenceEngine
from .actions import ActionIntelligenceEngine
from .sources import SourceIntelligenceEngine
from .evidence import EvidenceVerificationEngine
from .threat import ThreatIntelligenceEngine
from .fingerprints import ScamFingerprintEngine
from .policy import (
    PolicyInterventionEngine,
    PolicyDecision,
    PolicyDecisionType,
    InterventionScope,
    PolicySeverity,
    ReasonCode,
    POLICY_VERSION,
)
from .schemas import (
    ContentInput,
    NormalizedContent,
    SourceInfo,
    RawContent,
    NormalizedText,
    EntityItem,
    EntitiesContainer,
    UrlSignal,
    DomainSignal,
    SocialHandleSignal,
    RegistrationNumberSignal,
    CurrencyAmountSignal,
    PercentageSignal,
    DateSignal,
    CallToAction,
    StructuredSignals,
    ContentFeatures,
    Provenance,
    ClaimAnalysis,
    CanonicalClaim,
    ClaimRelation,
    ActionAnalysis,
    CanonicalAction,
    ActionRelation,
    SourceAnalysis,
    SourceDocument,
    EvidenceCandidate,
    ClaimSourceResult,
    ClaimVerificationStatus,
    EvidenceRelationType,
    EvidenceStrength,
    RegulatoryFinding,
    VerificationResult,
    EvidenceAnalysis,
    ThreatSignal,
    AttackNode,
    AttackTransition,
    AttackPath,
    ClaimActionLink,
    EvidenceWeakness,
    HighImpactAction,
    ThreatCombination,
    ThreatExplanation,
    FingerprintPreparation,
    ThreatProvenance,
    ThreatAnalysisMetadata,
    ThreatAnalysis,
    ScamFingerprint,
    FingerprintObservation,
    FingerprintMatch,
    FingerprintProvenance,
    FingerprintAnalysisMetadata,
    FingerprintAnalysis,
    FingerprintMatchType,
    FingerprintStatus,
)

__version__ = ENGINE_VERSION

__all__ = [
    "ContentIntelligenceEngine",
    "ClaimIntelligenceEngine",
    "ActionIntelligenceEngine",
    "SourceIntelligenceEngine",
    "EvidenceVerificationEngine",
    "ThreatIntelligenceEngine",
    "ScamFingerprintEngine",
    "ENGINE_VERSION",
    "ContentInput",
    "NormalizedContent",
    "SourceInfo",
    "RawContent",
    "NormalizedText",
    "EntityItem",
    "EntitiesContainer",
    "UrlSignal",
    "DomainSignal",
    "SocialHandleSignal",
    "RegistrationNumberSignal",
    "CurrencyAmountSignal",
    "PercentageSignal",
    "DateSignal",
    "CallToAction",
    "StructuredSignals",
    "ContentFeatures",
    "Provenance",
    "ClaimAnalysis",
    "CanonicalClaim",
    "ClaimRelation",
    "ActionAnalysis",
    "CanonicalAction",
    "ActionRelation",
    "SourceAnalysis",
    "SourceDocument",
    "EvidenceCandidate",
    "ClaimSourceResult",
    "ClaimVerificationStatus",
    "EvidenceRelationType",
    "EvidenceStrength",
    "RegulatoryFinding",
    "VerificationResult",
    "EvidenceAnalysis",
    "ThreatSignal",
    "AttackNode",
    "AttackTransition",
    "AttackPath",
    "ClaimActionLink",
    "EvidenceWeakness",
    "HighImpactAction",
    "ThreatCombination",
    "ThreatExplanation",
    "FingerprintPreparation",
    "ThreatProvenance",
    "ThreatAnalysisMetadata",
    "ThreatAnalysis",
    "ScamFingerprint",
    "FingerprintObservation",
    "FingerprintMatch",
    "FingerprintProvenance",
    "FingerprintAnalysisMetadata",
    "FingerprintAnalysis",
    "FingerprintMatchType",
    "FingerprintStatus",
    "PolicyInterventionEngine",
    "PolicyDecision",
    "PolicyDecisionType",
    "InterventionScope",
    "PolicySeverity",
    "ReasonCode",
    "POLICY_VERSION",
]


